// Code generated by coz. DO NOT EDIT.
/**
 * Mixins for the-scene
 * @module the-scene-mixins
 */
'use strict'

const _d = (m) => (m && 'default' in m) ? m.default : m

const bindDefaults_ = require('./bindDefaults')
const bindScope_ = require('./bindScope')
const compose_ = require('./compose')
const siteToast_ = require('./siteToast')
const withBack_ = require('./withBack')
const withBusy_ = require('./withBusy')
const withEntities_ = require('./withEntities')
const withEntry_ = require('./withEntry')
const withFailure_ = require('./withFailure')
const withFilter_ = require('./withFilter')
const withHistory_ = require('./withHistory')
const withHolder_ = require('./withHolder')
const withId_ = require('./withId')
const withLimit_ = require('./withLimit')
const withLocation_ = require('./withLocation')
const withPage_ = require('./withPage')
const withQuery_ = require('./withQuery')
const withReady_ = require('./withReady')
const withResult_ = require('./withResult')
const withSort_ = require('./withSort')
const withTargets_ = require('./withTargets')
const withValues_ = require('./withValues')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.bindDefaults = _d(bindDefaults_)
exports.bindScope = _d(bindScope_)
exports.compose = _d(compose_)
exports.siteToast = _d(siteToast_)
exports.withBack = _d(withBack_)
exports.withBusy = _d(withBusy_)
exports.withEntities = _d(withEntities_)
exports.withEntry = _d(withEntry_)
exports.withFailure = _d(withFailure_)
exports.withFilter = _d(withFilter_)
exports.withHistory = _d(withHistory_)
exports.withHolder = _d(withHolder_)
exports.withId = _d(withId_)
exports.withLimit = _d(withLimit_)
exports.withLocation = _d(withLocation_)
exports.withPage = _d(withPage_)
exports.withQuery = _d(withQuery_)
exports.withReady = _d(withReady_)
exports.withResult = _d(withResult_)
exports.withSort = _d(withSort_)
exports.withTargets = _d(withTargets_)
exports.withValues = _d(withValues_)

module.exports = {
  bindDefaults: _d(bindDefaults_),
  bindScope: _d(bindScope_),
  compose: _d(compose_),
  siteToast: _d(siteToast_),
  withBack: _d(withBack_),
  withBusy: _d(withBusy_),
  withEntities: _d(withEntities_),
  withEntry: _d(withEntry_),
  withFailure: _d(withFailure_),
  withFilter: _d(withFilter_),
  withHistory: _d(withHistory_),
  withHolder: _d(withHolder_),
  withId: _d(withId_),
  withLimit: _d(withLimit_),
  withLocation: _d(withLocation_),
  withPage: _d(withPage_),
  withQuery: _d(withQuery_),
  withReady: _d(withReady_),
  withResult: _d(withResult_),
  withSort: _d(withSort_),
  withTargets: _d(withTargets_),
  withValues: _d(withValues_),
}
