// Code generated by coz. DO NOT EDIT.
/**
 * Mixins for the-scene
 * @module the-scene-mixins
 */
'use strict'

const _d = (m) => 'default' in m ? m.default : m

module.exports = {
  get bindDefaults () { return _d(require('./bindDefaults')) },
  get bindScope () { return _d(require('./bindScope')) },
  get compose () { return _d(require('./compose')) },
  get siteToast () { return _d(require('./siteToast')) },
  get withBack () { return _d(require('./withBack')) },
  get withBusy () { return _d(require('./withBusy')) },
  get withEntities () { return _d(require('./withEntities')) },
  get withEntry () { return _d(require('./withEntry')) },
  get withFailure () { return _d(require('./withFailure')) },
  get withFilter () { return _d(require('./withFilter')) },
  get withHistory () { return _d(require('./withHistory')) },
  get withHolder () { return _d(require('./withHolder')) },
  get withId () { return _d(require('./withId')) },
  get withLocation () { return _d(require('./withLocation')) },
  get withPage () { return _d(require('./withPage')) },
  get withQuery () { return _d(require('./withQuery')) },
  get withReady () { return _d(require('./withReady')) },
  get withResult () { return _d(require('./withResult')) },
  get withSort () { return _d(require('./withSort')) },
  get withTargets () { return _d(require('./withTargets')) },
  get withValues () { return _d(require('./withValues')) },
}
